=== LinkedInLearning/linq-xml-2883064/source/BigStarCollectibles.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema"
					 targetNamespace="http://bigstarcollectibles.com/course-examples"
					 xmlns="http://bigstarcollectibles.com/course-examples BigStarCollectibles.xsd"
					 >
	
	<xs:element name="Collectibles">

		
		<xs:complexType>
			<xs:sequence>
			
							<xs:element maxOccurs="unbounded" name="Card">
								
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Slogan" type="xs:string"/>
										<xs:element name="Description" type="xs:string"/>
										<xs:element name="PublishedDate" type="xs:date"/>
										<xs:element name="ImageUri" type="xs:anyURI"/>
									
									
										<xs:element name="Prices">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="CatalogPrice" type="xs:decimal"/>
													<xs:element name="BidPrice" type="xs:decimal"/>
											
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element minOccurs="0" name="Robot">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="PowerSource"  >
														<xs:simpleType  >
															<xs:restriction base="xs:string">
																<xs:enumeration value="Fission" />
																<xs:enumeration value="Battery" />
																<xs:enumeration value="Solar" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element minOccurs="0" name="Monster">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Antenna" type="xs:boolean" />
													<xs:element name="Spikes" type="xs:boolean"/>
													<xs:element name="EyeCount" type="xs:integer"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="card-name" type="xs:string" use="required" />
									<xs:attribute name="team-name"  use="required" >
										<xs:simpleType  >
											<xs:restriction base="xs:string">
												<xs:enumeration value="BattleStars" />
												<xs:enumeration value="BlueShadows" />
												<xs:enumeration value="Thunderheads" />
												<xs:enumeration value="Spooktones" />
												<xs:enumeration value="Crashmasters" />
												<xs:enumeration value="Mavericks" />
												<xs:enumeration value="LaserPhasers" />
												<xs:enumeration value="Helios" />
												<xs:enumeration value="Farsiders" />
												<xs:enumeration value="SuperNovas" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="rarity"  use="optional" >
										<xs:simpleType  >
											<xs:restriction base="xs:string">
												<xs:enumeration value="Rare" />
												<xs:enumeration value="Uncommon" />
												<xs:enumeration value="Common" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="collector-number" type="xs:string" use="optional" />

									<xs:attribute name="card-family"  use="optional" >
										<xs:simpleType  >
											<xs:restriction base="xs:string">
												<xs:enumeration value="Monster" />
												<xs:enumeration value="Robot" />
												<xs:enumeration value="Alien" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								
								</xs:complexType>
							</xs:element>
						</xs:sequence>

		</xs:complexType>
	</xs:element>
</xs:schema>

=== LinkedInLearning/linq-xml-2883064/source/BigStarCollectibles-WithPrefix.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Example data for LinkedIn Learning course
     Course name: .NET Essentials: LINQ for XML

     Note: This XML example is for demonstration purposes. It contains data in elements and attributes.
     <Cards> represent a cards in collectible deck-building card games
-->

<bigstar:Collectibles xmlns:bigstar="http://bigstarcollectibles.com/course-examples"
											xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
											xsi:schemaLocation="bigstarcollectibles.com/course-examples BigStarCollectibles.xsd" >

	<bigstar:Card card-name="Mingle" team-name="BlueShadows" rarity="Rare" collector-number="31/249" card-family="Monster">
		<bigstar:Slogan>Double Trouble</bigstar:Slogan>
		<bigstar:Description>Mingle excels at doing twice the work in half the time, with pinpoint accuracy.  These skills serve her well in her role as Senior Data Analyst for an international cloud computing company. She's also got a penchant for ballroom dance, line dancing, and pretty much any kind of activity that lets her groove to music.</bigstar:Description>
			<bigstar:PublishedDate>2007-04-07</bigstar:PublishedDate>
				<bigstar:ImageUri>Monster-Mingle-card.png</bigstar:ImageUri>

		<bigstar:Prices>
			<bigstar:CatalogPrice>5.99</bigstar:CatalogPrice>
				<bigstar:BidPrice>15.95</bigstar:BidPrice>

			</bigstar:Prices>
		<bigstar:Monster>
			<bigstar:Antenna>false</bigstar:Antenna>
				<bigstar:Spikes>false</bigstar:Spikes>
					<bigstar:EyeCount>2</bigstar:EyeCount>
			</bigstar:Monster>
		</bigstar:Card>



</bigstar:Collectibles>

=== LinkedInLearning/linq-xml-2883064/source/BigStarCollectibles.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Example data for LinkedIn Learning course
     Course name: .NET Essentials: LINQ for XML

     Note: This XML example is for demonstration purposes. It contains data in elements and attributes.
		 Big Star Collectibles trades and sells collectible items.
		 A collectible is something of value either in a collection or to a collector.
     <Cards> represent a cards in collectible deck-building card games
-->

<Collectibles xmlns="http://bigstarcollectibles.com/course-examples"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="bigstarcollectibles.com/course-examples BigStarCollectibles.xsd">
	
		<Card card-name="Mingle" team-name="BlueShadows" rarity="Rare" collector-number="31/249" card-family="Monster">
			<Slogan>Double Trouble</Slogan>
			<Description>Mingle excels at doing twice the work in half the time, with pinpoint accuracy.  These skills serve her well in her role as Senior Data Analyst for an international cloud computing company. She's also got a penchant for ballroom dance, line dancing, and pretty much any kind of activity that lets her groove to music.</Description>
			<PublishedDate>2007-04-07</PublishedDate>
			<ImageUri>Monster-Mingle-card.png</ImageUri>

			<Prices>
				<CatalogPrice>5.99</CatalogPrice>
				<BidPrice>15.95</BidPrice>

			</Prices>
			<Monster>
				<Antenna>false</Antenna>
				<Spikes>false</Spikes>
				<EyeCount>2</EyeCount>
			</Monster>
		</Card>

		<Card card-name="Yodel" rarity="Uncommon" team-name="Spooktones" collector-number="47/249" card-family="Monster">
			<Slogan>Yodelay Hee Hoo!</Slogan>
			<Description>Yodel grew up in a family of singers and loud talkers and could never get a word in edgewise. Then his vast talent for yodeling emerged. Now he performs to adoring fans throughout the world, and always has the loudest voice at the dinner table. Incidentally, he's also a loud proponent of net neutrality, and spends countless hours moderating an internet forum devoted solely to that subject.</Description>
			<PublishedDate>2018-05-05</PublishedDate>
			<ImageUri>Monster-Mingle-card.png</ImageUri>
			<Prices>
				<CatalogPrice>5.99</CatalogPrice>
				<BidPrice>6.95</BidPrice>

			</Prices>

			<Monster>
				<Antenna>false</Antenna>
				<Spikes>true</Spikes>
				<EyeCount>2</EyeCount>
			</Monster>

		</Card>
		<Card card-name="Squido" rarity="Uncommon" team-name="Thunderheads" collector-number="17/249" card-family="Monster">
			<Slogan>An Eye for Design</Slogan>
			<Description>Squido's got his hands or rather tentacles, in everything. First and foremost, he's a web designer with an eye for visual aesthetics, but he's also rather keen on UX design and making sure what he creates translates optimally to the end user. In his off-hours he's an avid nature photographer and bowler.</Description>
			<PublishedDate>2014-07-05</PublishedDate>
			<ImageUri>Monster-Squido-card.png</ImageUri>
			<Prices>
				<CatalogPrice>2.99</CatalogPrice>
				<BidPrice>13.95</BidPrice>

			</Prices>

			<Monster>
				<Antenna>false</Antenna>
				<Spikes>true</Spikes>
				<EyeCount>2</EyeCount>
			</Monster>

		</Card>
		<Card card-name="Skedaddle" rarity="Rare" team-name="Spooktones" collector-number="204/249" card-family="Monster">
			<Slogan>Game of Life</Slogan>
			<Description>When Skedaddle was a teenager, his parents couldn't keep him away from his Game Boy. In fact, they seriously worried that he might not find a suitable career.  Now as a prominent game developer for Red30 Tech, he's found his true callingâ€¦and put his family's worries to rest. You probably could have guessed this, but in his spare time Skedaddle loves to pay computer games.</Description>
			<PublishedDate>2019-10-28</PublishedDate>
			<ImageUri>Monster-Skedaddle-card.png</ImageUri>
			<Prices>
				<CatalogPrice>7.99</CatalogPrice>
				<BidPrice>26.95</BidPrice>

			</Prices>

			<Monster>
				<Antenna>false</Antenna>
				<Spikes>false</Spikes>
				<EyeCount>1</EyeCount>
			</Monster>

		</Card>

		<Card card-name="Rex" rarity="Uncommon" team-name="Crashmasters" collector-number="06/143" card-family="Robot">
			<Slogan>Great Microcontrollers Think Alike</Slogan>
			<Description>
				Rex is the Mayor of Binaryville, and a well-loved personality in town. He rose to robotdom from a microprocessor plant on the south side of town, where many famous and influential robots before him were conceived.
			</Description>
			<PublishedDate>2016-09-16</PublishedDate>
			<ImageUri>Robot-Rex-card.png</ImageUri>
			<Prices>
				<CatalogPrice>5.99</CatalogPrice>
				<BidPrice>17.95</BidPrice>

			</Prices>

			<Robot>
				<PowerSource>Battery</PowerSource>

			</Robot>

		</Card>
		<Card card-name="Rivet" rarity="Common" team-name="Mavericks" collector-number="58/143" card-family="Robot">
			<Slogan>Hauling mud since 2012</Slogan>
			<Description>
				Rivet descended from an assembly line of amphibious robots, but never quite took to deep water - though he does love rolling around in mucky marshes and soaking up the mud on vacation. With his advanced temperature sensors and all-weather construction, he's often dispatched to remote regions all around the world to help with disaster relief work.
			</Description>
			<PublishedDate>2016-09-16</PublishedDate>
			<ImageUri>Robot-Rivet-card.png</ImageUri>
			<Prices>
				<CatalogPrice>6.99</CatalogPrice>
				<BidPrice>3.95</BidPrice>

			</Prices>

			<Robot>
				<PowerSource>Fission</PowerSource>

			</Robot>

		</Card>
		<Card card-name="Cosmo" rarity="Rare" team-name="Crashmasters" collector-number="141/143" card-family="Robot">
			<Slogan>To Mars and back</Slogan>
			<Description>
				For an esteemed aeronautical engineer who manned the first ever flight to Mars from Binaryville (or anywhere), Cosmo is one of the most down-to-earth folks you'll ever meet. His favorite pastimes are playing bingo, soaking up the sun at Binaryville Beach, and reading spy novels.
			</Description>
			<PublishedDate>2017-01-03</PublishedDate>
			<ImageUri>Robot-Cosmo-card.png</ImageUri>
			<Prices>
				<CatalogPrice>6.99</CatalogPrice>
				<BidPrice>33.95</BidPrice>

			</Prices>

			<Robot>
				<PowerSource>Solar</PowerSource>

			</Robot>

		</Card>
	

</Collectibles>
